{% set version = '1.9' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-vcpen
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/vcpen_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/vcpen/vcpen_{{ version }}.tar.gz
  sha256: 25567c0a175d2d03ccf33815c1a4105029c2a24be81c77438219c59393a5e53d

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ stdlib('c') }}                # [not win]
    - {{ stdlib('m2w64_c') }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-rcpp >=1.0.0               # [build_platform != target_platform]
    - r-rcpparmadillo >=0.8.0      # [build_platform != target_platform]
    - r-knitr                      # [build_platform != target_platform]
  host:
    - libblas
    - liblapack
    - r-base
    - r-rcpp >=1.0.0
    - r-rcpparmadillo >=0.8.0
    - r-knitr
  run:
    - r-base
    - r-rcpp >=1.0.0
    - r-rcpparmadillo >=0.8.0
    - r-knitr

test:
  commands:
    - $R -e "library('vcpen')"           # [not win]
    - "\"%R%\" -e \"library('vcpen')\""  # [win]

about:
  home: https://cran.r-project.org/package=vcpen
  license: GPL-3.0-or-later
  summary: Method to perform penalized variance component analysis.
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: vcpen
# Type: Package
# Title: Penalized Variance Components Analysis
# Version: 1.9
# Date: 2022-01-02
# Authors@R: c(person("Jason", "Sinnwell", email = "sinnwell.jason@mayo.edu", comment=c(ORCID="0000-0003-1964-5522"), role = c("aut","cre"),), person("Daniel", "Schaid", email = "schaid.daniel@mayo.edu", comment=c(ORCID="0000-0003-1457-6433"), role = c("aut")))
# Description: Method to perform penalized variance component analysis.
# License: GPL (>= 3)
# Suggests: rmarkdown, testthat
# Depends: R (>= 4.0.0), methods
# Imports: knitr, Rcpp (>= 1.0.0), RcppArmadillo (>= 0.8.0)
# LinkingTo: Rcpp, RcppArmadillo
# NeedsCompilation: yes
# RoxygenNote: 7.1.2
# VignetteBuilder: knitr
# URL: https://cran.r-project.org/package=vcpen
# Packaged: 2022-01-03 15:18:57 UTC; sinnwell
# Author: Jason Sinnwell [aut, cre] (<https://orcid.org/0000-0003-1964-5522>), Daniel Schaid [aut] (<https://orcid.org/0000-0003-1457-6433>)
# Maintainer: Jason Sinnwell <sinnwell.jason@mayo.edu>
# Repository: CRAN
# Date/Publication: 2022-01-03 16:40:02 UTC
